name: multiphenicsx CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  test:
    uses: multiphenics/multiphenicsx/.github/workflows/flake8_tests_tutorials.yml@main
    with:
      repository: "multiphenics/multiphenicsx"
      library: "multiphenicsx"
    secrets:
      REPO_ACCESS_TOKEN: ""

  docker:
    uses: multiphenics/multiphenicsx/.github/workflows/docker.yml@main
    needs: [test]
    if: github.ref == 'refs/heads/main'
    with:
      library: "multiphenicsx"
      image_name: "multiphenics/multiphenicsx"
      release_if_repository: "multiphenics/multiphenicsx"
    secrets:
      CI_REGISTRY_USER: "${{ secrets.CI_REGISTRY_USER }}"
      CI_REGISTRY_PASSWORD: "${{ secrets.CI_REGISTRY_PASSWORD }}"
