name: Test against releases packaged by conda

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  warn:
    runs-on: ubuntu-latest
    if: github.repository == 'multiphenics/multiphenicsx' && github.ref == 'refs/heads/main' && github.event_name == 'schedule'
    steps:
      - name: Warn if scheduled workflow is about to be disabled
        uses: fem-on-colab/warn-workflow-about-to-be-disabled-action@main
        with:
          workflow-filename: conda_against_releases.yml
          days-elapsed: 55
